### PR TITLE
Fixed lstrip bug, replaced with split

### PR DESCRIPTION
**Pull request by mdelcambre**
lstrip() takes a list of characters as the argument string, not a string to remove.
lstrip('www.') will remove all 'w' and '.' from the start of the url (functionally equivalent to lstrip('w.')). If the domain begins with 'w' it will strip that too:
> 'www.whirlpool.com'.lstrip('www.')
>'hirlpool.com'

Changed to use url.split('www.',1)[1]. This splits the string a maximum of one time (from the left) on the separator 'www.'. This will give us an array of an empty string and the domain. This will not function properly if handed the url 'http://www.com'. To deal with this edge case a regular expression may be best.
$ python
>>> 'www.www.com'.split('www.',1)[1]
'www.com'

### CODE REVIEW

**Comment by dangra** [comment]
good catch but your proposal raise IndexError if the hostname doesn't contain `www.`, what about using `[-1]` as index.

```python
>>> 'www.scrapinghub.com'.split('www.')[1]
'scrapinghub.com'
>>> 'scrapinghub.com'.split('www.')[1]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-d8840f20fa65> in <module>()
----> 1 'scrapinghub.com'.split('www.')[1]

IndexError: list index out of range
>>> 'scrapinghub.com'.split('www.')[-1]
'scrapinghub.com'
```

**Comment by mdelcambre** [comment]
You are absolutely right. however this also breaks on the rare domain that
ends in 'www'.
>>> 'examplewww.com'.split('www.')[-1]
'com'

It seems the choice is either to allow some edge cases to fail or write a
fairly complex regular expression.
If you decide to go with allowing some edge cases to fail, it seems that
the one you have proposed is a strong candidate.

**Comment by mdelcambre** [comment]
I guess there is an intermediate regex. would only really fail on the
domain 'www.[tld]'
>>> import re
>>> tests = ['www.examplewww.com','examplewww.com','www.example.com','
example.com','www.com','www.www.com']
>>> for test in tests:
...     print(test+' ->'),
...     print(re.sub(r'^www\.','',test))
...
www.examplewww.com -> examplewww.com
examplewww.com -> examplewww.com
www.example.com -> example.com
example.com -> example.com
www.com -> com
www.www.com -> www.com

**Comment by mdelcambre** [comment]
I guess there is an intermediate regex ('^www\.') . It would only really fail on the domain 'www.[tld]' but i don't know if you want to import re for this simple task.
```python
>>> import re
>>> tests = ['www.examplewww.com','examplewww.com','www.example.com','example.com','www.com','www.www.com']
>>> for test in tests:
...     print(test+' ->'),
...     print(re.sub(r'^www\.','',test))
...
www.examplewww.com -> examplewww.com
examplewww.com -> examplewww.com
www.example.com -> example.com
example.com -> example.com
www.com -> com
www.www.com -> www.com
```

**Comment by dangra** [comment]
I'm ok with the solution that cover most cases and do not depend on external libraries. So let's use regex.

**Comment by mdelcambre** [comment]
I apologize, haven't done much in terms of pull requests on github. I guess that I could have simply edited this pull request.

**Comment by dangra** [comment]
The usual workflow is to fix the issue in the same branch you used to create the pull request and push,  GitHub takes care of listing the commits on this PR ticket then.

but now I realize you are using the web to edit and create pull request, so I understand.

**Pull request closed without merging**
